import type { Plugin } from '@terrazzo/parser';

const NATIVE_RADIUS_TOKENS = [
  ['card', 'semantic.radius.card'],
  ['panel', 'semantic.radius.panel'],
] as const;

function readPxDimension(value: unknown, id: string): number {
  if (typeof value !== 'object' || value === null) {
    throw new Error(`${id} must resolve to a DTCG dimension object.`);
  }

  const dimension = value as Record<string, unknown>;

  if (typeof dimension.value !== 'number' || dimension.unit !== 'px') {
    throw new Error(
      `${id} must resolve to a px dimension before Native generation.`,
    );
  }

  return dimension.value;
}

export default function nativePlugin(): Plugin {
  return {
    name: 'dante-native-tokens',
    build({ tokens, outputFile }) {
      const output = [
        '/* This file is generated by Terrazzo. Do not edit manually. */',
        '',
        'export const radii = {',
      ];

      for (const [localName, tokenId] of NATIVE_RADIUS_TOKENS) {
        const token = tokens[tokenId];

        if (!token || token.$type !== 'dimension') {
          throw new Error(`${tokenId} must exist and be a dimension token.`);
        }

        output.push(
          `  ${localName}: ${readPxDimension(token.$value, tokenId)},`,
        );
      }

      output.push(
        '} as const;',
        '',
        'export type RadiusToken = keyof typeof radii;',
        '',
      );

      outputFile('native.ts', output.join('\n'));
    },
  };
}
