import { parseTimelineDate } from './timeline-temporal';
import type { TimelineEvent, TimelineGroup } from './timeline-types';

export const TIMELINE_PROTOTYPE_TODAY = parseTimelineDate('2026-08-04');
export const TIMELINE_PROTOTYPE_NOW_MINUTE = 14 * 60 + 20;

export const TIMELINE_GROUPS: readonly TimelineGroup[] = [
  { id: 'focus', label: 'Focus / lavoro profondo', tone: 'focus' },
  { id: 'riunioni', label: 'Riunioni', tone: 'meeting' },
  { id: 'salute', label: 'Salute', tone: 'health' },
  { id: 'creativita', label: 'Creatività', tone: 'creative' },
  { id: 'personale', label: 'Personale', tone: 'personal' },
  { id: 'urgenze', label: 'Urgenze', tone: 'urgent' },
];

export const TIMELINE_PROTOTYPE_EVENTS: Readonly<
  Record<string, readonly TimelineEvent[]>
> = {
  '2026-08-04': [
    {
      id: '1',
      startMinute: 8 * 60,
      endMinute: 8 * 60 + 30,
      title: 'Routine mattutina',
      groupId: 'personale',
      meta: 'Casa',
    },
    {
      id: '2',
      startMinute: 9 * 60,
      endMinute: 11 * 60,
      title: 'Redesign LifeOS — sessione focus',
      groupId: 'focus',
      meta: 'Progetto LifeOS',
      subitems: [
        'Rivedi layout Home',
        'Verifica componenti',
        'Aggiorna note UX',
      ],
    },
    {
      id: '3',
      startMinute: 9 * 60 + 30,
      endMinute: 10 * 60 + 15,
      title: 'Team sync',
      groupId: 'riunioni',
      meta: 'Google Meet',
    },
    {
      id: '4',
      startMinute: 11 * 60 + 45,
      endMinute: 12 * 60 + 30,
      title: 'Call cliente — revisione onboarding',
      groupId: 'riunioni',
      meta: 'Cliente · Preparazione',
    },
    {
      id: '5',
      startMinute: 12 * 60 + 30,
      endMinute: 13 * 60 + 15,
      title: 'Pausa pranzo',
      groupId: 'personale',
      meta: 'Ricarica',
    },
    {
      id: '6',
      startMinute: 13 * 60 + 15,
      endMinute: 14 * 60,
      title: 'Allenamento — mobilità',
      groupId: 'salute',
      meta: '20 min',
    },
    {
      id: '7',
      startMinute: 14 * 60,
      endMinute: 15 * 60,
      title: 'Studio — grammatica avanzata',
      groupId: 'focus',
      meta: 'Certificazione B2',
    },
    {
      id: '8',
      startMinute: 14 * 60 + 30,
      endMinute: 15 * 60 + 15,
      title: 'Revisione concept',
      groupId: 'creativita',
      meta: 'Nuove funzionalità',
    },
    {
      id: '12',
      startMinute: 14 * 60 + 45,
      endMinute: 15 * 60,
      title: 'Promemoria',
      groupId: 'personale',
      meta: 'Entro oggi',
    },
    {
      id: '9',
      startMinute: 15 * 60 + 15,
      endMinute: 16 * 60 + 15,
      title: 'Ideazione concept — nuove funzionalità',
      groupId: 'creativita',
      meta: 'Sessione libera',
    },
    {
      id: '10',
      startMinute: 16 * 60 + 30,
      endMinute: 17 * 60 + 30,
      title: 'Scrittura documentazione',
      groupId: 'focus',
      meta: 'Specifiche e linee guida',
    },
    {
      id: '11',
      startMinute: 17 * 60 + 30,
      endMinute: 18 * 60,
      title: 'Debrief attività & next steps',
      groupId: 'riunioni',
      meta: 'Chiusura giornata',
    },
    {
      id: '13',
      startMinute: 18 * 60 + 30,
      endMinute: 19 * 60 + 30,
      title: 'Allenamento — corsa',
      groupId: 'salute',
      meta: 'Circuito parco',
      subitems: ['Riscaldamento', 'Corsa intensa', 'Recupero', 'Stretching'],
    },
  ],
  '2026-08-05': [
    {
      id: '101',
      startMinute: 9 * 60,
      endMinute: 10 * 60,
      title: 'Standup settimanale',
      groupId: 'riunioni',
      meta: 'Google Meet',
    },
    {
      id: '102',
      startMinute: 10 * 60 + 30,
      endMinute: 12 * 60,
      title: 'Lavoro su proposta cliente',
      groupId: 'focus',
      meta: 'Nuovo cliente',
    },
    {
      id: '103',
      startMinute: 14 * 60,
      endMinute: 15 * 60,
      title: 'Palestra',
      groupId: 'salute',
      meta: 'Sala pesi',
    },
    {
      id: '104',
      startMinute: 16 * 60,
      endMinute: 16 * 60 + 30,
      title: 'Lettura e pianificazione',
      groupId: 'personale',
      meta: 'Obiettivi',
    },
  ],
  '2026-08-06': [
    {
      id: '201',
      startMinute: 8 * 60 + 30,
      endMinute: 10 * 60,
      title: 'Focus — implementazione',
      groupId: 'focus',
      meta: 'LifeOS',
    },
    {
      id: '202',
      startMinute: 11 * 60,
      endMinute: 11 * 60 + 45,
      title: 'Review tecnica',
      groupId: 'riunioni',
      meta: 'Team',
    },
    {
      id: '203',
      startMinute: 15 * 60,
      endMinute: 16 * 60,
      title: 'Fotografia — selezione scatti',
      groupId: 'creativita',
      meta: 'Archivio',
    },
  ],
  '2026-08-07': [
    {
      id: '301',
      startMinute: 9 * 60,
      endMinute: 11 * 60,
      title: 'Deep work',
      groupId: 'focus',
      meta: 'Progetto',
    },
    {
      id: '302',
      startMinute: 18 * 60,
      endMinute: 19 * 60,
      title: 'Camminata',
      groupId: 'salute',
      meta: 'Outdoor',
    },
  ],
};
