"""Registered SQLAlchemy mappings for the materialized DANTE schema."""

from typing import cast

from sqlalchemy import Table

from . import (
    actual,
    addressing,
    auth,
    email_delivery,
    identity,
    lifecycle,
    occurrence_generation,
    recurrence,
    schedule,
    session,
)

MAPPED_TABLES: tuple[Table, ...] = cast(
    tuple[Table, ...],
    (
        identity.PersonRow.__table__,
        identity.LivingReferentRow.__table__,
        identity.AssetRow.__table__,
        identity.PlaceRow.__table__,
        identity.ContentArtifactRow.__table__,
        identity.CollectiveRow.__table__,
        identity.PossibilityRow.__table__,
        identity.GoalRow.__table__,
        identity.PlanRow.__table__,
        identity.ActivityRow.__table__,
        identity.EventRow.__table__,
        identity.RoutineRow.__table__,
        identity.OccurrenceRow.__table__,
        identity.SessionRow.__table__,
        identity.ObservationRow.__table__,
        addressing.NativeAddressRow.__table__,
        addressing.ScopedAddressRow.__table__,
        addressing.MaterialStateAddressRow.__table__,
        lifecycle.MaterialStateRetirementRow.__table__,
        addressing.NativeCurrentMaterialStateRow.__table__,
        addressing.ScopedCurrentMaterialStateRow.__table__,
        schedule.ScheduleRow.__table__,
        actual.ActualRow.__table__,
        schedule.SchedulePlacementStateRow.__table__,
        schedule.SchedulePlacementDateStateRow.__table__,
        schedule.SchedulePlacementFloatingLocalStateRow.__table__,
        schedule.SchedulePlacementNamedZoneStateRow.__table__,
        schedule.SchedulePlacementAbsoluteStateRow.__table__,
        schedule.SchedulePlacementCurrentHistoryRow.__table__,
        actual.ActualRealizationStateRow.__table__,
        actual.ActualRealizationTimingRow.__table__,
        actual.ActualRealizationSessionBasisRow.__table__,
        actual.ActualRealizationCurrentHistoryRow.__table__,
        session.SessionTimingStateRow.__table__,
        session.SessionTimingAbsoluteRow.__table__,
        session.SessionTimingElapsedRow.__table__,
        session.SessionTimingPauseRow.__table__,
        session.SessionTimingCurrentHistoryRow.__table__,
        recurrence.RoutineRecurrenceStateRow.__table__,
        recurrence.RoutineRecurrenceCurrentHistoryRow.__table__,
        recurrence.RoutineRecurrenceBoundaryStateRow.__table__,
        recurrence.RoutineRecurrenceCalendarStateRow.__table__,
        recurrence.RoutineRecurrenceCalendarWallTimeRow.__table__,
        recurrence.RoutineRecurrenceCalendarWeekdayRow.__table__,
        recurrence.RoutineRecurrenceCalendarMonthDayRow.__table__,
        recurrence.RoutineRecurrenceCalendarOrdinalWeekdayRow.__table__,
        recurrence.RoutineRecurrenceCalendarYearMonthDayRow.__table__,
        recurrence.RoutineRecurrenceElapsedStateRow.__table__,
        recurrence.RoutineRecurrenceQuotaStateRow.__table__,
        recurrence.RoutineRecurrenceCyclicStateRow.__table__,
        recurrence.RoutineRecurrenceCyclePositionRow.__table__,
        recurrence.EventRecurrenceStateRow.__table__,
        recurrence.EventRecurrenceCurrentHistoryRow.__table__,
        recurrence.EventRecurrenceBoundaryStateRow.__table__,
        recurrence.EventRecurrenceCalendarStateRow.__table__,
        recurrence.EventRecurrenceCalendarWallTimeRow.__table__,
        recurrence.EventRecurrenceCalendarWeekdayRow.__table__,
        recurrence.EventRecurrenceCalendarMonthDayRow.__table__,
        recurrence.EventRecurrenceCalendarOrdinalWeekdayRow.__table__,
        recurrence.EventRecurrenceCalendarYearMonthDayRow.__table__,
        recurrence.EventRecurrenceElapsedStateRow.__table__,
        recurrence.EventRecurrenceQuotaStateRow.__table__,
        recurrence.EventRecurrenceCyclicStateRow.__table__,
        recurrence.EventRecurrenceCyclePositionRow.__table__,
        occurrence_generation.OccurrenceGenerationRow.__table__,
        occurrence_generation.OccurrenceGenerationCalendarRow.__table__,
        occurrence_generation.OccurrenceGenerationElapsedRow.__table__,
        occurrence_generation.OccurrenceGenerationQuotaRow.__table__,
        occurrence_generation.OccurrenceGenerationCyclicRow.__table__,
        auth.AccountRow.__table__,
        auth.EmailIdentityRow.__table__,
        auth.PasswordCredentialRow.__table__,
        auth.AuthSessionRow.__table__,
        auth.PasswordSignupChallengeRow.__table__,
        auth.PasswordRecoveryChallengeRow.__table__,
        auth.ExternalIdentityRow.__table__,
        auth.ExternalAuthTransactionRow.__table__,
        auth.AppleAuthGrantRow.__table__,
        auth.ExternalLinkChallengeRow.__table__,
        auth.ExternalSignupChallengeRow.__table__,
        auth.AccountProfileBootstrapRow.__table__,
        auth.WebAuthnAccountRow.__table__,
        auth.PasskeyCredentialRow.__table__,
        auth.WebAuthnChallengeRow.__table__,
        email_delivery.EmailDeliveryIntentRow.__table__,
        email_delivery.EmailDeliveryAttemptRow.__table__,
        email_delivery.EmailProviderEventRow.__table__,
        email_delivery.EmailRecipientSuppressionRow.__table__,
    ),
)

__all__ = ["MAPPED_TABLES"]
