import type { access as itAccess } from '../it/access';

type AccessResource<T> = T extends string
  ? string
  : { readonly [K in keyof T]: AccessResource<T[K]> };

export const access = {
  stage: {
    titleFirst: 'Understand life.',
    titleSecond: 'Shape what comes next.',
    body: 'A personal space to understand what is happening, preserve continuity over time, and decide what comes next.',
    foot: 'One reality. More than one way to understand it.',
  },
  kicker: {
    access: 'Access',
    setup: 'Initial setup',
  },
  signin: {
    title: 'Sign in to DANTE',
    body: 'Continue with your account or use email and password.',
    forgot: 'Forgot password?',
    new: 'New to DANTE?',
  },
  signup: {
    title: 'Create your DANTE account',
    body: 'Use an email address you can access. We’ll ask you to verify it.',
    existing: 'Already have an account?',
    progress: 'Account creation progress',
    stepEmail: 'Email',
    stepPassword: 'Password',
    stepVerify: 'Verify',
    continueEmail: 'Continue with email',
    orProvider: 'or create your account with',
    google: 'Create with Google',
    apple: 'Create with Apple',
  },
  signupPassword: {
    title: 'Protect your account',
    body: 'Choose a long, unique password. You can use one generated by your password manager.',
  },
  password: {
    guideTitle: 'Minimum length',
    proposal: '12+ characters',
    manager: 'You can paste or generate the password with your password manager.',
  },
  provider: {
    google: 'Continue with Google',
    apple: 'Continue with Apple',
    body: 'DANTE opens the provider’s official flow. The consent screen belongs to the provider, not DANTE.',
    wait: 'Opening provider…',
    scopeNote: 'Google/Apple sign-in authenticates your account. It does not automatically grant access to Calendar, Gmail, or iCloud.',
  },
  common: {
    or: 'or',
  },
  field: {
    email: 'Email',
    emailPlaceholder: 'name@example.com',
    password: 'Password',
    verificationCode: 'Verification code',
  },
  action: {
    signin: 'Sign in',
    createAccount: 'Create account',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    continue: 'Continue',
    cancel: 'Cancel',
    changeEmail: 'Change email',
    backSignin: 'Back to sign in',
    tryAgain: 'Try again',
    back: 'Back',
  },
  validation: {
    email: 'Enter a valid email address.',
    passwordRequired: 'Enter your password.',
    passwordMinimum: 'Use at least 12 characters.',
    passwordMismatch: 'The passwords do not match.',
    verificationCode: 'Enter the 6-digit code.',
  },
  integration: {
    title: 'Frontend ready, backend pending',
    body: 'This action is already wired into the Access flow. The real authentication service will complete it without simulating an outcome.',
  },
  network: {
    offlineTitle: 'You’re offline.',
    offlineBody: 'Reconnect to continue.',
    rateLimitedTitle: 'Too many attempts.',
    rateLimitedBody: 'Wait before trying again. The effective retry time will come from the server.',
    serverUnavailableTitle: 'Service temporarily unavailable.',
    serverUnavailableBody: 'Try again when the Access service is reachable.',
  },
  locale: {
    control: 'Change language. Current language: {{language}}',
    options: 'Available languages',
  },
  legal: {
    prefix: 'By continuing, you agree to the',
    terms: 'Terms',
    privacy: 'Privacy',
  },
  verify: {
    title: 'Check your email',
    body: 'Enter the 6-digit code we sent to verify the address.',
    resend: 'Send again',
    action: 'Verify and continue',
    privacy: 'The code is single-use and expires automatically.',
  },
  forgot: {
    title: 'Recover access',
    body: 'We’ll send a secure link to set a new password.',
    action: 'Send recovery link',
    privacy: 'The response is intentionally neutral: we do not confirm whether an address is registered.',
  },
  recovery: {
    title: 'Check your email',
    body: 'If an account exists for the address you entered, you’ll receive instructions to recover access.',
  },
  reset: {
    title: 'Create a new password',
    body: 'The new password will replace the previous one.',
    new: 'New password',
    confirm: 'Confirm password',
    action: 'Update password',
    doneTitle: 'Password updated',
    doneBody: 'You can now sign in with the new password.',
  },
  providerError: {
    title: 'Sign-in not completed',
    body: 'The provider did not complete authentication. No changes were applied to your account.',
    safe: 'Your account is safe.',
    retry: 'Try again or choose another method.',
  },
  link: {
    title: 'Confirm account linking',
    body: 'A DANTE account already exists for this email. Sign in to that account before linking the provider.',
    action: 'Sign in and link',
    other: 'Use another account',
  },
  authenticated: {
    title: 'Access confirmed',
    body: 'The DANTE session has been established. The handoff to Home will be connected to the real authenticated router.',
  },
  reauth: {
    title: 'Session expired',
    body: 'Sign in again to continue. The current context is not restored until the backend confirms the new authentication.',
  },
  setupName: {
    title: 'What should DANTE call you?',
    body: 'This only makes the experience more natural. You can change it anytime.',
    label: 'Preferred name',
  },
  setupLocale: {
    title: 'Language and time zone',
    body: 'DANTE uses these to show dates and times correctly. We prefilled what we can reliably detect.',
    note: 'We are not inferring preferences here; you are confirming operational settings.',
    language: 'Language',
    timezone: 'Time zone',
  },
  setupStart: {
    title: 'Where do you want to start?',
    body: 'Pick a path. None of these choices are permanent.',
  },
  start: {
    real: 'Create something real',
    realBody: 'An event, activity, routine, or goal.',
    import: 'Import something you already use',
    importBody: 'Bring in an existing calendar or file.',
    demo: 'Show me a quick demo',
    demoBody: 'Try the interaction without creating real data.',
    skip: 'Explore on my own',
    skipBody: 'Enter Home now. You can resume guidance later.',
  },
  firstAction: {
    title: 'Create your first real thing',
    body: 'Start with something simple. You can add details later.',
    label: 'What do you want to add?',
    action: 'Create and open Home',
  },
  importFlow: {
    title: 'Import into your space',
    body: 'Import is separate from sign-in: using Google to log in does not authorize DANTE to read your calendar.',
    google: 'Google import will require a separate, explicit authorization.',
    file: 'You’ll be able to import a calendar file without linking an account.',
  },
  demo: {
    title: 'A demo that never pollutes your data',
    body: 'The item below is tutorial-only and never enters your real history.',
    item: 'Walk · 6:30 PM',
    itemBody: 'You can open, move, complete, or delete it during the tour.',
    action: 'Start demo and open Home',
  },
  home: {
    title: 'You’re ready',
    body: 'Initial setup is complete. DANTE opens Home from here and guidance continues only when useful.',
    pending: 'This screen is ready; the handoff to canonical Home intentionally waits for the real session and authenticated router.',
  },
} as const satisfies AccessResource<typeof itAccess>;
